### ISSUE TITLE
POTCAR

### ISSUE THREAD

**Issue by will9508** [alejandrosantanabonilla/PSO#1]
Hi 

Could you give more detail about POTCAR, in the POTCAR file, should the user put the substrate's pseudopotential first or the cluster's pseudopotential first?

Also, could this code merge the POTCAR by itself?

Like in the test, there should be C element in the substrate and Mo element in the cluster. Then you could ask the user to provide the POTCAR separately, like C_POTCAR and Mo_POTCAR. Then the code will accord the POSCAR file (created by the code) to detect which POTCAR it needs and merge them to a new POTCAR for calculation.

**Comment by alejandrosantanabonilla** [comment]
That file needs to be provided by the user. I consider this issue closed.
